"""Searchable, editable metadata for each document.

Every uploaded document has a Knowledge Bank entry linked by source_document_id
(see kb_ingestion_service). Its tags, summary, type, status and execution date
are the document's metadata: generated by the user's LLM during ingestion and
editable by anyone who can access the document.

Access is checked against the document itself (owner or matter member), not the
entry's KB scope, so metadata never reveals a document the user cannot open.
"""

import logging
import re
from datetime import date
from typing import Any

from sqlalchemy import String, cast, desc, func, or_, select
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Session

from app.models import Document, KnowledgeBankEntry, Matter, User
from app.providers.embedding_provider import EmbeddingError, embed_texts
from app.services.catalogue_service import (
    DOCUMENT_STATUSES,
    DOCUMENT_TYPES,
    MAX_SUMMARY,
    apply_catalogue,
    normalise_tags,
)
from app.services.document_service import can_access_document, document_access_filter
from app.services.knowledge_bank_service import (
    KnowledgeBankError,
    _embed_entry,
    _embedding_is_stale,
    log_kb_access,
)
from app.services.resource_metadata_service import sync_kb_metadata, sync_metadata_safe


_log = logging.getLogger(__name__)


class DocumentMetadataError(Exception):
    pass


def _summary(entry: KnowledgeBankEntry) -> str | None:
    fields = entry.catalogue_fields if isinstance(entry.catalogue_fields, dict) else {}
    value = fields.get("summary")
    return value if isinstance(value, str) and value else None


def metadata_to_dict(entry: KnowledgeBankEntry, document: Document, matter_name: str | None) -> dict[str, Any]:
    fields = entry.catalogue_fields if isinstance(entry.catalogue_fields, dict) else {}
    return {
        "document_id": document.id,
        "entry_id": entry.id,
        "filename": document.filename,
        "matter_id": document.matter_id,
        "matter_name": matter_name,
        "status": entry.status,
        "tags": list(entry.tags or []),
        "summary": _summary(entry),
        "document_type": entry.document_type,
        "document_status": entry.document_status,
        "execution_date": entry.execution_date,
        "parties": fields.get("parties") or [],
        "key_dates": fields.get("key_dates") or [],
        "edited_fields": fields.get("edited_fields") or [],
        "updated_at": entry.updated_at,
    }


def _metadata_entry(db: Session, document_id: str) -> KnowledgeBankEntry | None:
    return db.scalar(
        select(KnowledgeBankEntry)
        .where(
            KnowledgeBankEntry.source_document_id == document_id,
        )
        .order_by(KnowledgeBankEntry.created_at)
        .limit(1)
    )


def get_document_metadata(db: Session, *, user: User, document_id: str) -> dict[str, Any] | None:
    """Return the document's metadata, or None if it is missing or not accessible."""
    document = db.get(Document, document_id)
    if not document or not can_access_document(db, user_id=user.id, document=document):
        return None
    entry = _metadata_entry(db, document.id)
    if not entry:
        return None
    matter = db.get(Matter, document.matter_id) if document.matter_id else None
    return metadata_to_dict(entry, document, matter.title if matter else None)


async def update_document_metadata(
    db: Session,
    *,
    user: User,
    document_id: str,
    updates: dict[str, Any],
) -> dict[str, Any] | None:
    """Apply a person's edits and pin those fields against later re-extraction."""
    document = db.get(Document, document_id)
    if not document or not can_access_document(db, user_id=user.id, document=document):
        return None
    entry = _metadata_entry(db, document.id)
    if not entry:
        return None

    fields = dict(entry.catalogue_fields) if isinstance(entry.catalogue_fields, dict) else {}
    edited = set(fields.get("edited_fields") or [])
    if "tags" in updates:
        entry.tags = normalise_tags(updates["tags"] or [])
        edited.add("tags")
    if "summary" in updates:
        summary = (updates["summary"] or "").strip()[:MAX_SUMMARY]
        fields["summary"] = summary or None
        edited.add("summary")
    if "document_type" in updates:
        if updates["document_type"] not in DOCUMENT_TYPES:
            raise DocumentMetadataError(f"document_type must be one of {list(DOCUMENT_TYPES)}")
        entry.document_type = updates["document_type"]
        edited.add("document_type")
    if "document_status" in updates:
        if updates["document_status"] not in DOCUMENT_STATUSES:
            raise DocumentMetadataError(f"document_status must be one of {list(DOCUMENT_STATUSES)}")
        entry.document_status = updates["document_status"]
        edited.add("document_status")
    if "execution_date" in updates:
        value: date | None = updates["execution_date"]
        entry.execution_date = value
        fields["execution_date"] = value.isoformat() if value else None
        edited.add("execution_date")
    fields["edited_fields"] = sorted(edited)
    entry.catalogue_fields = fields
    entry.version += 1

    if _embedding_is_stale(entry):
        try:
            await _embed_entry(entry)
        except KnowledgeBankError:
            # The edit still saves; the hash mismatch leaves the entry stale, so
            # the embedding backfill picks it up later.
            pass
    try:
        log_kb_access(db, user_id=user.id, entry_id=entry.id, matter_id=entry.matter_id, commit=False)
        db.commit()
    except Exception:
        db.rollback()
        raise
    sync_metadata_safe(db, sync_kb_metadata, entry)
    return get_document_metadata(db, user=user, document_id=document.id)


def list_document_tags(db: Session, *, user: User, matter_id: str | None = None, limit: int = 200) -> list[str]:
    """Distinct tags across documents the user can access, most used first."""
    tag = func.jsonb_array_elements_text(cast(KnowledgeBankEntry.tags, JSONB)).table_valued("value").alias("tag")
    stmt = (
        select(tag.c.value, func.count().label("uses"))
        .select_from(KnowledgeBankEntry)
        .join(Document, KnowledgeBankEntry.source_document_id == Document.id)
        .join(tag, func.true())
        .where(KnowledgeBankEntry.source_document_id.is_not(None), document_access_filter(user.id))
    )
    if matter_id:
        stmt = stmt.where(Document.matter_id == matter_id)
    stmt = stmt.group_by(tag.c.value).order_by(desc("uses"), tag.c.value).limit(limit)
    return [row[0] for row in db.execute(stmt).all()]


async def search_document_catalogue(
    db: Session,
    *,
    user: User,
    query: str | None = None,
    tags: list[str] | None = None,
    document_type: str | None = None,
    matter_id: str | None = None,
    limit: int = 10,
) -> list[dict[str, Any]]:
    """Find documents by their metadata.

    Tags are an AND filter (exact, case-insensitive). The query ranks by vector
    similarity on the entry embedding (title, tags, summary, body), falling back
    to keyword matching on title, filename and tags if embedding is unavailable.
    """
    stmt = (
        select(KnowledgeBankEntry, Document, Matter.title)
        .join(Document, KnowledgeBankEntry.source_document_id == Document.id)
        .outerjoin(Matter, Document.matter_id == Matter.id)
        .where(
            document_access_filter(user.id),
            Document.status == "ready",
        )
    )
    if matter_id:
        stmt = stmt.where(Document.matter_id == matter_id)
    if document_type:
        stmt = stmt.where(KnowledgeBankEntry.document_type == document_type)
    for wanted in normalise_tags(tags or []):
        stmt = stmt.where(cast(KnowledgeBankEntry.tags, JSONB).contains([wanted]))

    query = (query or "").strip()
    rows: list
    if query:
        try:
            query_embedding = (await embed_texts([query]))[0]
        except EmbeddingError:
            query_embedding = None
        if query_embedding is not None:
            distance = KnowledgeBankEntry.embedding.cosine_distance(query_embedding)
            rows = db.execute(
                stmt.where(KnowledgeBankEntry.embedding.is_not(None)).order_by(distance).limit(limit)
            ).all()
        else:
            terms = re.findall(r"[A-Za-z0-9]{3,}", query)[:8]
            text_match = [
                or_(
                    KnowledgeBankEntry.title.ilike(f"%{term}%"),
                    Document.filename.ilike(f"%{term}%"),
                    cast(KnowledgeBankEntry.tags, String).ilike(f"%{term.lower()}%"),
                )
                for term in terms
            ]
            if text_match:
                stmt = stmt.where(or_(*text_match))
            rows = db.execute(stmt.order_by(desc(Document.created_at)).limit(limit)).all()
    else:
        rows = db.execute(stmt.order_by(desc(Document.created_at)).limit(limit)).all()

    return [metadata_to_dict(entry, document, matter_name) for entry, document, matter_name in rows]



MAX_INGEST_CHARS_BACKFILL = 60_000

# Entries made before metadata existed have the placeholder tag "from document", so the
# marker for "not catalogued yet" is a missing summary, not empty tags.
_NO_SUMMARY = func.coalesce(KnowledgeBankEntry.catalogue_fields["summary"].as_string(), "") == ""


async def backfill_document_metadata(db: Session, *, limit: int = 10) -> dict[str, int]:
    """Re-run only the catalogue pass for document entries that have no summary yet.

    Leaves the entry body and title alone (unlike the KB worker), so text a person
    has edited is not rewritten. Runs on each entry creator's own key. Returns
    counts. Entries that cannot be catalogued stay in `remaining`, so callers should
    stop when a batch makes no progress.
    """
    from app.models import DocumentChunk
    from app.services.catalogue_service import extract_catalogue
    from app.services.llm_service import get_llm
    from app.services.kb_ingestion_service import FORMAT_TIMEOUT_SECONDS

    pending = list(
        db.scalars(
            select(KnowledgeBankEntry)
            .where(
                KnowledgeBankEntry.status == "ready",
                KnowledgeBankEntry.source_document_id.is_not(None),
                _NO_SUMMARY,
            )
            .order_by(KnowledgeBankEntry.created_at)
            .limit(limit)
        )
    )
    updated = skipped = 0
    for entry in pending:
        document = db.get(Document, entry.source_document_id)
        chunks = list(
            db.scalars(
                select(DocumentChunk.text)
                .where(DocumentChunk.document_id == entry.source_document_id)
                .order_by(DocumentChunk.chunk_index)
            )
        )
        raw_text = "\n\n".join(chunks)
        if not document or not raw_text:
            skipped += 1
            continue
        try:
            provider = get_llm(db, entry.created_by, feature="kb_format")
        except Exception as exc:  # noqa: BLE001 - no usable key for this owner
            _log.warning("Metadata backfill skipped for %s: %s", entry.id, exc)
            skipped += 1
            continue
        catalogue = await extract_catalogue(
            provider,
            filename=document.filename,
            raw_text=raw_text,
            max_chars=MAX_INGEST_CHARS_BACKFILL,
            timeout=FORMAT_TIMEOUT_SECONDS,
        )
        if not catalogue:
            skipped += 1
            continue
        apply_catalogue(entry, catalogue)
        entry.embedding_content_hash = None  # re-embed with the new tags and summary
        try:
            if _embedding_is_stale(entry):
                await _embed_entry(entry)
        except KnowledgeBankError:
            pass  # stays stale; the regular backfill retries
        entry.version += 1
        db.commit()
        sync_metadata_safe(db, sync_kb_metadata, entry)
        updated += 1

    remaining = db.scalar(
        select(func.count())
        .select_from(KnowledgeBankEntry)
        .where(
            KnowledgeBankEntry.status == "ready",
            KnowledgeBankEntry.source_document_id.is_not(None),
            _NO_SUMMARY,
        )
    ) or 0
    return {"updated": updated, "skipped": skipped, "remaining": remaining}
